# Generated by Django 4.2.11 on 2026-03-27 13:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='titulo')),
                ('description', models.TextField(verbose_name='descricao')),
                ('activity_type', models.CharField(choices=[('assignment', 'Tarefa'), ('quiz', 'Quiz'), ('forum', 'Forum'), ('poll', 'Enquete')], default='assignment', max_length=20, verbose_name='tipo')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='prazo')),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nota maxima')),
                ('is_published', models.BooleanField(default=False, verbose_name='publicada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
            ],
            options={
                'verbose_name': 'atividade',
                'verbose_name_plural': 'atividades',
                'ordering': ['due_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='codigo')),
                ('title', models.CharField(max_length=150, verbose_name='titulo')),
                ('description', models.TextField(verbose_name='descricao')),
                ('syllabus', models.TextField(blank=True, verbose_name='ementa')),
                ('workload_hours', models.PositiveIntegerField(default=0, verbose_name='carga horaria')),
                ('is_published', models.BooleanField(default=False, verbose_name='publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses_taught', to=settings.AUTH_USER_MODEL, verbose_name='professor')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Estudante'), ('teacher', 'Professor')], default='student', max_length=20, verbose_name='papel')),
                ('academic_id', models.CharField(blank=True, max_length=30, verbose_name='matricula')),
                ('bio', models.TextField(blank=True, verbose_name='biografia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'perfil de usuario',
                'verbose_name_plural': 'perfis de usuario',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='conteudo')),
                ('attachment_url', models.URLField(blank=True, verbose_name='link do anexo')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('submitted', 'Enviada'), ('reviewed', 'Avaliada'), ('late', 'Enviada com atraso')], default='draft', max_length=20, verbose_name='status')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='enviada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nota')),
                ('feedback', models.TextField(blank=True, verbose_name='feedback')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='avaliada em')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='agora.activity', verbose_name='atividade')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL, verbose_name='avaliada por')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='estudante')),
            ],
            options={
                'verbose_name': 'entrega',
                'verbose_name_plural': 'entregas',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='titulo')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ordem')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='agora.course', verbose_name='curso')),
            ],
            options={
                'verbose_name': 'modulo',
                'verbose_name_plural': 'modulos',
                'ordering': ['course', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('completed', 'Concluida'), ('cancelled', 'Cancelada')], default='active', max_length=20, verbose_name='status')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='matriculado em')),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nota final')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='agora.course', verbose_name='curso')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='estudante')),
            ],
            options={
                'verbose_name': 'matricula',
                'verbose_name_plural': 'matriculas',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='agora.course', verbose_name='curso'),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities_created', to=settings.AUTH_USER_MODEL, verbose_name='criada por'),
        ),
        migrations.AddField(
            model_name='activity',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='agora.module', verbose_name='modulo'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('activity', 'student'), name='unique_submission_per_activity_student'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_module_order_per_course'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_student_enrollment'),
        ),
    ]
