# Generated by Django 4.2.11 on 2026-03-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='module',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='biografia'),
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
