# Generated by Django 4.2.11 on 2026-03-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0002_remove_activity_module_alter_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('assignment', 'Tarefa'), ('quiz', 'Quiz'), ('forum', 'Fórum'), ('poll', 'Enquete')], default='assignment', max_length=20, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Ativa'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='active', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Estudante'), ('teacher', 'Professor(a)')], default='student', max_length=20, verbose_name='papel'),
        ),
    ]
