# Generated by Django 4.2.11 on 2026-03-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0003_alter_activity_activity_type_alter_enrollment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('active', 'Ativa'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='active', max_length=20, verbose_name='status'),
        ),
    ]
