# Generated by Django 6.0.3 on 2026-04-12 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0004_alter_enrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='attachment_url',
            field=models.URLField(blank=True, verbose_name='link de anexo'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('assignment', 'Tarefa'), ('quiz', 'Quiz'), ('forum', 'Fórum'), ('poll', 'Enquete'), ('resource', 'Material')], default='assignment', max_length=20, verbose_name='tipo'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='titulo')),
                ('description', models.TextField(blank=True, default='', verbose_name='descricao')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ordem')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='agora.course', verbose_name='modulo')),
            ],
            options={
                'verbose_name': 'modulo',
                'verbose_name_plural': 'modulos',
                'ordering': ['course', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='agora.module', verbose_name='modulo'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_module_order_per_course'),
        ),
    ]
