# Generated by Django 6.0.3 on 2026-04-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0006_reduce_activity_types'),
        ('agora', '0008_normalize_userprofile_cpf_digits'),
    ]

    operations = [
    ]
