# Generated by Django 4.2.11 on 2026-04-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0011_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('assignment', 'Tarefa'), ('quiz', 'Quiz'), ('forum', 'Fórum'), ('resource', 'Material')], default='assignment', max_length=20, verbose_name='tipo'),
        ),
    ]
