# Generated by Django 4.2.11 on 2026-04-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0012_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='attachment_file',
            field=models.FileField(blank=True, null=True, upload_to='activity_materials/', verbose_name='arquivo de anexo'),
        ),
    ]
