# Generated by Django 4.2.11 on 2026-04-21 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0014_courseitem_inheritance_refactor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
    ]
