# Generated by Django 4.2.11 on 2026-04-21 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0015_remove_userprofile_bio'),
        ('agora', '0017_quizquestion_image'),
    ]

    operations = [
    ]
